export const movies = [
  { name: 'The Shawshank Redemption', year: 1994, rating: 9.2 },
  { name: 'The Godfather', year: 1972, rating: 9.1 },
  { name: 'The Godfather: Part II', year: 1974, rating: 9.0 },
  { name: 'The Dark Knight', year: 2008, rating: 9.0 },
  { name: '12 Angry Men', year: 1957, rating: 8.9 },
  { name: "Schindler's List", year: 1993, rating: 8.9 },
  { name: 'The Lord of the Rings: The Return of the King', year: 2003, rating: 8.9 },
  { name: 'Pulp Fiction', year: 1994, rating: 8.8 },
  { name: 'The Good, the Bad and the Ugly ', year: 1966, rating: 8.8 },
  { name: 'The Lord of the Rings: The Fellowship of the Ring', year: 2001, rating: 8.8 },
  { name: 'Fight Club', year: 1999, rating: 8.8 },
  { name: 'Forrest Gump', year: 1994, rating: 8.7 },
  { name: 'Inception', year: 2010, rating: 8.7 },
  { name: 'The Lord of the Rings: The Two Towers', year: 2002, rating: 8.7 },
  { name: 'Star Wars: Episode V - The Empire Strikes Back', year: 1980, rating: 8.7 },
  { name: 'The Matrix', year: 1999, rating: 8.6 },
  { name: 'Goodfellas', year: 1990, rating: 8.6 },
  { name: "One Flew Over the Cuckoo's Nest", year: 1975, rating: 8.6 },
  { name: 'Seven Samurai', year: 1954, rating: 8.6 },
  { name: 'Se7en', year: 1995, rating: 8.6 },
  { name: 'The Silence of the Lambs', year: 1991, rating: 8.6 },
  { name: 'City of God', year: 2002, rating: 8.6 },
  { name: 'Life Is Beautiful', year: 1997, rating: 8.6 },
  { name: "It's a Wonderful Life", year: 1946, rating: 8.6 },
  { name: 'Star Wars: Episode IV - A New Hope', year: 1977, rating: 8.6 },
  { name: 'Saving Private Ryan', year: 1998, rating: 8.5 },
  { name: 'Interstellar', year: 2014, rating: 8.5 },
  { name: 'Spirited Away', year: 2001, rating: 8.5 },
  { name: 'The Green Mile', year: 1999, rating: 8.5 },
  { name: 'Parasite', year: 2019, rating: 8.5 },
];
